// Generates SEO-friendly reports as HTML served by the API.

export function buildReportFromTrends({ trends, lang='en' }){
  const date = new Date().toISOString().slice(0,10);
  const title = lang==='tr' ? `Günlük Trend Raporu (${date})` : lang==='es' ? `Informe Diario (${date})` : `Daily Trend Report (${date})`;
  const body = trends.slice(0,10).map((t,i)=>{
    return `<h2>${i+1}. ${escapeHtml(t.term)}</h2>
      <p><b>Region:</b> ${t.region} &nbsp; <b>Category:</b> ${t.category}</p>
      <p><b>Momentum:</b> ${t.momentum}% &nbsp; <b>Velocity:</b> ${t.velocity}</p>
      <p>${escapeHtml(t.summary||'')}</p>
      <p><b>Sources:</b> ${(t.sources||[]).join(', ')}</p>`;
  }).join('
');

  const html = `<!doctype html><html lang="${lang}"><head><meta charset="utf-8"/><meta name="viewport" content="width=device-width,initial-scale=1"/>
  <title>${escapeHtml(title)}</title>
  <meta name="description" content="${escapeHtml(title)}"/>
  </head><body style="font-family:system-ui;background:#0b1020;color:#fff;max-width:900px;margin:0 auto;padding:24px;line-height:1.65">
  <h1>${escapeHtml(title)}</h1>
  <p style="color:#a3b5d6">Automated report generated by TrendGlobe.</p>
  ${body}
  <hr/><p style="color:#93a4c2;font-size:12px">Disclaimer: informational only. No financial advice.</p>
  </body></html>`;

  const slug = `report-${date}-${lang}`;
  return { slug, title, html, publishedAt: new Date().toISOString() };
}

function escapeHtml(s){
  return String(s).replace(/[&<>"']/g, c => ({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
}
